{"name": "Ошибка при проверке пользователя с некорректным паролем", "status": "passed", "start": 1717593114673, "stop": 1717593114969, "uuid": "3fcba21e-785a-43f4-95c6-e2928de069b3", "historyId": "2c4672d592c7795c458c6f9b0bbbeeb4", "testCaseId": "2c4672d592c7795c458c6f9b0bbbeeb4", "fullName": "tests.py.test_user.TestUserLogin#test_login_incorrect_password_failed_result", "labels": [{"name": "parentSuite", "value": "tests.py"}, {"name": "suite", "value": "test_user"}, {"name": "subSuite", "value": "TestUserLogin"}, {"name": "host", "value": "DESKTOP-AQPR8BL"}, {"name": "thread", "value": "18104-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.py.test_user"}]}