{"name": "Ошибка при проверке пользователя с некорректным паролем", "status": "passed", "start": 1717592840320, "stop": 1717592840557, "uuid": "02557a40-b0dc-4f17-b5f1-12fe550c88c7", "historyId": "2c4672d592c7795c458c6f9b0bbbeeb4", "testCaseId": "2c4672d592c7795c458c6f9b0bbbeeb4", "fullName": "tests.py.test_user.TestUserLogin#test_login_incorrect_password_failed_result", "labels": [{"name": "parentSuite", "value": "tests.py"}, {"name": "suite", "value": "test_user"}, {"name": "subSuite", "value": "TestUserLogin"}, {"name": "host", "value": "DESKTOP-AQPR8BL"}, {"name": "thread", "value": "6544-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.py.test_user"}]}