{"name": "Ошибка при проверке пользователя с некорректным паролем", "status": "passed", "start": 1717767621937, "stop": 1717767622317, "uuid": "c1d6d5ec-03b5-4135-a6cc-0d14c9c1313d", "historyId": "2c4672d592c7795c458c6f9b0bbbeeb4", "testCaseId": "2c4672d592c7795c458c6f9b0bbbeeb4", "fullName": "tests.py.test_user.TestUserLogin#test_login_incorrect_password_failed_result", "labels": [{"name": "parentSuite", "value": "tests.py"}, {"name": "suite", "value": "test_user"}, {"name": "subSuite", "value": "TestUserLogin"}, {"name": "host", "value": "DESKTOP-AQPR8BL"}, {"name": "thread", "value": "16524-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.py.test_user"}]}