{"name": "Ошибка проверки получения заказов неавторизованного пользователя", "status": "passed", "start": 1717767608641, "stop": 1717767608966, "uuid": "98c649a8-ed6e-4795-ba63-2f201ccbe873", "historyId": "4211f6c8720dca9d714cc0c4c31b625a", "testCaseId": "4211f6c8720dca9d714cc0c4c31b625a", "fullName": "tests.py.test_order.TestUserOrderGetting#test_getting_order_unauthorized_user", "labels": [{"name": "parentSuite", "value": "tests.py"}, {"name": "suite", "value": "test_order"}, {"name": "subSuite", "value": "TestUserOrderGetting"}, {"name": "host", "value": "DESKTOP-AQPR8BL"}, {"name": "thread", "value": "16524-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.py.test_order"}]}