{"name": "Успешная проверка получения заказов авторизованного пользователя", "status": "failed", "statusDetails": {"message": "AssertionError: assert (401 == 200)\n +  where 401 = <Response [401]>.status_code", "trace": "self = <test_order.TestUserOrderGetting object at 0x00000222DFA9FDA0>, user = {'access_token': None, 'email': '753@ya.ru', 'name': 'ubpumtb', 'password': 1267472}\norder_making = 3891\n\n    @allure.title('Успешная проверка получения заказов авторизованного пользователя')\n    def test_getting_order_authorized_user(self, user, order_making):\n        headers = {'Authorization': user['access_token']}\n        response = requests.get(data.user_order, headers=headers)\n>       assert response.status_code == 200 and response.json()['orders'][0]['number'] == order_making\nE       assert (401 == 200)\nE        +  where 401 = <Response [401]>.status_code\n\ntests.py\\test_order.py:41: AssertionError"}, "start": 1717767607604, "stop": 1717767607910, "uuid": "c1421d3c-4b43-4bde-a4f4-0b580edefb34", "historyId": "2f087c1e1afcb21261a38dc4c350a246", "testCaseId": "2f087c1e1afcb21261a38dc4c350a246", "fullName": "tests.py.test_order.TestUserOrderGetting#test_getting_order_authorized_user", "labels": [{"name": "parentSuite", "value": "tests.py"}, {"name": "suite", "value": "test_order"}, {"name": "subSuite", "value": "TestUserOrderGetting"}, {"name": "host", "value": "DESKTOP-AQPR8BL"}, {"name": "thread", "value": "16524-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.py.test_order"}]}